spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        # --- USER SERVICE ROUTE ---
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/user/** # If the URL starts with this... route it to the URI above

        # --- GROUP SERVICE ROUTE ---
        - id: group-service
          uri: ${GROUP_SERVICE_URL}
          predicates:
            - Path=/api/groups/**

        # --- EXPENSE SERVICE ROUTE ---
        - id: expense-service
          uri: ${EXPENSE_SERVICE_URL}
          predicates:
            - Path=/api/expenses/**

        # --- SETTLEMENT SERVICE ROUTE ---
        - id: settlement-service
          uri: ${SETTLEMENT_SERVICE_URL}
          predicates:
            - Path=/api/settlements/**

        # --- NOTIFICATION SERVICE ROUTE ---
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL}
          predicates:
            - Path=/api/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          # If using Firebase, the issuer is https://securetoken.google.com/<YOUR_PROJECT_ID>
          issuer-uri: https://securetoken.google.com/${FIREBASE_PROJECT_ID}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      # Groups APIs logically in the UI
      tags-sorter: alpha
      operations-sorter: alpha
    # Customizing the OpenAPI info via YAML (can also be done in a @Configuration class)
    openapi:
      info:
        title: API Gateway for Splitwise
        version: 1.0.0
        description: API for managing Splitwise groups, expenses, settlements, and notifications
      components:
        securitySchemes:
          UserIdHeader:
            type: apiKey
            in: header
            name: X-User-Id
      security:
        - UserIdHeader: [ ]

server:
  port: 8090

