server:
  port: 8084

spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/splitwise_settlements
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  rabbitmq:
    addresses: ${AWS_RABBITMQ_ENDPOINT}
    listener:
      simple:
        concurrency: 5 # Process 5 messages in parallel
        max-concurrency: 10
        acknowledge-mode: auto

# OpenAPI/Swagger settings
springdoc:
  api-docs:
    path: /v3/api-docs